### ISSUE TITLE
Cannot create property 'render' on string 'react'

### ISSUE THREAD

**Issue by carlitux** [strawbrary/koa-nunjucks-2#13]
app.use(async (ctx, next) => {
    await ctx.render('react', {});
  });

**Comment by strawbrary** [comment]
Could you post the full stack trace for the error? We don't add properties to the template name so I'm not sure where that error is coming from.

**Comment by carlitux** [comment]
``` bash
Mon May 23 2016 20:02:10 GMT-0400 (BOT) ERROR   TypeError: Cannot create property 'render' on string 'react'
      at _callee2$ (/Users/carlitux/Projects/yaparime.bo/node_modules/koa-nunjucks-2/compiled.js:98:40)
      at tryCatch (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/regenerator/runtime.js:88:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/regenerator/runtime.js:341:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/regenerator/runtime.js:121:21)
      at step (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-polyfill/node_mGET /companies 500 8.866 ms - 78
odules/core-js/modules/es6.promise.js:193:7)
      at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
      at Object.<anonymous> (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
      at Object.render (/Users/carlitux/Projects/yaparime.bo/node_modules/koa-nunjucks-2/compiled.js:140:18)
      at _callee$ (companies.js:3:15)
      at tryCatch (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-regenerator-runtime/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-regenerator-runtime/runtime.js:329:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-regenerator-runtime/runtime.js:94:21)
      at invoke (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-regenerator-runtime/runtime.js:136:37)
      at callInvokeWithMethodAndArg (/Users/carlitux/Projects/yaparime.bo/node_modules/babel-regenerator-runtime/runtime.js:172:16)
```

**Comment by strawbrary** [comment]
It looks like one of the middleware that is executing before `koa-nunjucks-2` is overwriting the `ctx` object with a string. If possible try removing that overwriting and it should fix the error.

**Comment by carlitux** [comment]
I found... I was using the master README and I should use https://github.com/strawbrary/koa-nunjucks-2/tree/v3.0.0-alpha.3 that README
